# Generated by Django 5.2 on 2026-02-03 17:33

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.DateField(blank=True, help_text='Starting date for all students in this batch', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_fallback', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
            ],
            options={
                'verbose_name': 'FCM Device',
                'verbose_name_plural': 'FCM Devices',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_no', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Institute',
                'verbose_name_plural': 'Institutes',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notice')),
                ('message', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='notice_file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.IntegerField(blank=True, default=1, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('Year', 'Year Based'), ('Semester', 'Semester Based')], max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batches', models.ManyToManyField(blank=True, related_name='courses', to='app.batch')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='OTPAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('password', models.CharField(editable=False, max_length=128, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parent_images/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this parent belongs to.', related_name='parents', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this parent.', related_name='parent_set', related_query_name='parent', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ParentInstituteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('General', 'General'), ('Facilities', 'Facilities'), ('Teaching', 'Teaching'), ('Infrastructure', 'Infrastructure'), ('Administration', 'Administration')], default='General', max_length=20)),
                ('rating', models.DecimalField(choices=[(1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0)], decimal_places=1, max_digits=2)),
                ('feedback_text', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_feedbacks', to='app.institute')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_feedbacks', to='app.parent')),
            ],
            options={
                'verbose_name': 'Parent Institute Feedback',
                'verbose_name_plural': 'Parent Institute Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(unique=True)),
                ('identifier', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='app_resetto_token_759106_idx'), models.Index(fields=['expires_at'], name='app_resetto_expires_6efbaf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('temporary_address', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorced', 'Divorced')], max_length=255, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('citizenship_no', models.CharField(blank=True, max_length=255, null=True)),
                ('passport', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff_image')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('password', models.CharField(editable=False, max_length=128, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=500, null=True)),
                ('course', models.ForeignKey(blank=True, help_text='Course for which this staff member is HOD', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod', to='app.course')),
                ('courses_taught', models.ManyToManyField(blank=True, related_name='teachers', to='app.course')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this staff belongs to.', related_name='staffs', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this staff.', related_name='staff_set', related_query_name='staff', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period_or_year', models.PositiveIntegerField(help_text='Period number (semester or year) for this routine')),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('teacher_attend', models.BooleanField(default=True)),
                ('class_status', models.BooleanField(default=True)),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app.routine')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app.staff')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
        migrations.CreateModel(
            name='StaffInstituteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('General', 'General'), ('Facilities', 'Facilities'), ('Teaching', 'Teaching'), ('Infrastructure', 'Infrastructure'), ('Administration', 'Administration')], default='General', max_length=20)),
                ('rating', models.DecimalField(choices=[(1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0)], decimal_places=1, max_digits=2)),
                ('feedback_text', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_feedbacks', to='app.institute')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_feedbacks', to='app.staff')),
            ],
            options={
                'verbose_name': 'Staff Institute Feedback',
                'verbose_name_plural': 'Staff Institute Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('message', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
            options={
                'verbose_name': 'Staff Leave',
                'verbose_name_plural': 'Staff Leaves',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Leave', 'Leave'), ('Completed', 'Completed')], max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('temporary_address', models.CharField(blank=True, max_length=500, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=500, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorced', 'Divorced')], max_length=255, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('citizenship_no', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_image')),
                ('current_period', models.PositiveIntegerField(default=1, help_text="Current semester/year for the student's course")),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('password', models.CharField(editable=False, max_length=128, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=500, null=True)),
                ('batches', models.ManyToManyField(blank=True, related_name='students', to='app.batch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.course')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this student belongs to.', related_name='students', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this student.', related_name='student_set', related_query_name='student', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ParentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0)], decimal_places=1, max_digits=2)),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.parent')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_feedbacks', to='app.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_feedbacks', to='app.student')),
            ],
            options={
                'verbose_name': 'Parent Feedback',
                'verbose_name_plural': 'Parent Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(related_name='parents', to='app.student'),
        ),
        migrations.CreateModel(
            name='InstituteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('General', 'General'), ('Facilities', 'Facilities'), ('Teaching', 'Teaching'), ('Infrastructure', 'Infrastructure'), ('Administration', 'Administration')], default='General', max_length=20)),
                ('rating', models.DecimalField(choices=[(1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0)], decimal_places=1, max_digits=2)),
                ('feedback_text', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_feedbacks', to='app.student')),
            ],
            options={
                'verbose_name': 'Student Institute Feedback',
                'verbose_name_plural': 'Student Institute Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('progress_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], default='In Progress', max_length=20)),
                ('completion_percentage', models.IntegerField(default=0, help_text='Percentage of course completion (0-100)')),
                ('current_period', models.PositiveIntegerField(default=1, help_text='Current semester/year depending on course duration type')),
                ('period_start_date', models.DateField(blank=True, help_text='Start date of current semester/year', null=True)),
                ('period_end_date', models.DateField(blank=True, help_text='End date of current semester/year', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_trackings', to='app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_trackings', to='app.student')),
            ],
            options={
                'verbose_name': 'Course Tracking',
                'verbose_name_plural': 'Course Trackings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_attend', models.BooleanField(default=False)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.attendance')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0)], decimal_places=1, max_digits=2)),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.staff')),
            ],
            options={
                'verbose_name': 'Student Feedback',
                'verbose_name_plural': 'Student Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('message', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='app.student')),
            ],
            options={
                'verbose_name': 'Student Leave',
                'verbose_name_plural': 'Student Leaves',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('period_or_year', models.PositiveIntegerField(help_text='Period number (semester or year) for this subject')),
                ('syllabus_pdf', models.FileField(blank=True, help_text='Upload syllabus or study material PDF', null=True, upload_to='subject_pdfs/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
            options={
                'ordering': ['course', 'period_or_year', 'name'],
            },
        ),
        migrations.AddField(
            model_name='routine',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
        migrations.CreateModel(
            name='SubjectFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='subject_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.staff')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], default='Not Started', max_length=20)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_progress', to='app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='app.subject')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='TeacherParentMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField()),
                ('duration', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('agenda', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('meeting_link', models.URLField(blank=True, help_text='For online meetings')),
                ('is_online', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-meeting_date', '-meeting_time'],
                'indexes': [models.Index(fields=['meeting_date'], name='app_teacher_meeting_63c895_idx'), models.Index(fields=['status'], name='app_teacher_status_00033b_idx'), models.Index(fields=['is_online'], name='app_teacher_is_onli_ca0e10_idx'), models.Index(fields=['meeting_date', 'status'], name='app_teacher_meeting_d915da_idx'), models.Index(fields=['status', 'is_online'], name='app_teacher_status_f46524_idx')],
                'unique_together': {('meeting_date', 'meeting_time')},
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='meetings',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='app.teacherparentmeeting'),
        ),
        migrations.CreateModel(
            name='TOTPSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['identifier'], name='app_totpsec_identif_3b24b5_idx'), models.Index(fields=['expires_at'], name='app_totpsec_expires_5bf7fe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='app_course_name_c3d697_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='app_course_code_c9fdd9_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='app_course_is_acti_552db1_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['duration_type'], name='app_course_duratio_e1ef6d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name', 'is_active'], name='app_course_name_010d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code', 'is_active'], name='app_course_code_8559ac_idx'),
        ),
        migrations.AddIndex(
            model_name='otpattempt',
            index=models.Index(fields=['identifier'], name='app_otpatte_identif_2e1b10_idx'),
        ),
        migrations.AddIndex(
            model_name='otpattempt',
            index=models.Index(fields=['is_locked'], name='app_otpatte_is_lock_8ed6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='otpattempt',
            index=models.Index(fields=['lock_until'], name='app_otpatte_lock_un_0c1f72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parentinstitutefeedback',
            unique_together={('parent', 'institute', 'feedback_type')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='app_attenda_date_9b28e9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['routine'], name='app_attenda_routine_fa7d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['teacher'], name='app_attenda_teacher_a70a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_status'], name='app_attenda_class_s_55bcab_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'routine'], name='app_attenda_date_cc693f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['teacher', 'date'], name='app_attenda_teacher_811486_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['routine', 'class_status'], name='app_attenda_routine_344201_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffinstitutefeedback',
            unique_together={('staff', 'institute', 'feedback_type')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['phone'], name='app_student_phone_82dede_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='app_student_status_1ef7f6_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course'], name='app_student_course__31acd8_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['current_period'], name='app_student_current_1463ab_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['joining_date'], name='app_student_joining_e36cd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parentfeedback',
            unique_together={('parent', 'teacher', 'student')},
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['phone'], name='app_parent_phone_86404f_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['is_active'], name='app_parent_is_acti_504729_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['phone', 'is_active'], name='app_parent_phone_9a72b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='institutefeedback',
            unique_together={('user', 'institute', 'feedback_type')},
        ),
        migrations.AddIndex(
            model_name='coursetracking',
            index=models.Index(fields=['student'], name='app_courset_student_f2e52e_idx'),
        ),
        migrations.AddIndex(
            model_name='coursetracking',
            index=models.Index(fields=['course'], name='app_courset_course__9f370a_idx'),
        ),
        migrations.AddIndex(
            model_name='coursetracking',
            index=models.Index(fields=['progress_status'], name='app_courset_progres_2cc4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='coursetracking',
            index=models.Index(fields=['current_period'], name='app_courset_current_f4ba9b_idx'),
        ),
        migrations.AddIndex(
            model_name='coursetracking',
            index=models.Index(fields=['enrollment_date'], name='app_courset_enrollm_0a7d19_idx'),
        ),
        migrations.AddIndex(
            model_name='coursetracking',
            index=models.Index(fields=['student', 'progress_status'], name='app_courset_student_d53f12_idx'),
        ),
        migrations.AddIndex(
            model_name='coursetracking',
            index=models.Index(fields=['course', 'progress_status'], name='app_courset_course__320963_idx'),
        ),
        migrations.AddIndex(
            model_name='coursetracking',
            index=models.Index(fields=['student', 'course', 'progress_status'], name='app_courset_student_ff7d06_idx'),
        ),
        migrations.AddIndex(
            model_name='coursetracking',
            index=models.Index(fields=['completion_percentage'], name='app_courset_complet_05e331_idx'),
        ),
        migrations.AddIndex(
            model_name='coursetracking',
            index=models.Index(fields=['start_date', 'expected_end_date'], name='app_courset_start_d_52e928_idx'),
        ),
        migrations.AddIndex(
            model_name='coursetracking',
            index=models.Index(fields=['current_period', 'progress_status'], name='app_courset_current_486a84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursetracking',
            unique_together={('student', 'course')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['attendance'], name='app_attenda_attenda_6ba702_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student'], name='app_attenda_student_bfd4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student_attend'], name='app_attenda_student_630ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'student_attend'], name='app_attenda_student_6845cd_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['attendance', 'student'], name='app_attenda_attenda_8ae2e3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['attendance', 'student_attend'], name='app_attenda_attenda_12b1f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentfeedback',
            unique_together={('student', 'teacher')},
        ),
        migrations.AddIndex(
            model_name='studentleave',
            index=models.Index(fields=['student'], name='app_student_student_3dc1c4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentleave',
            index=models.Index(fields=['status'], name='app_student_status_f34c08_idx'),
        ),
        migrations.AddIndex(
            model_name='studentleave',
            index=models.Index(fields=['start_date'], name='app_student_start_d_da5199_idx'),
        ),
        migrations.AddIndex(
            model_name='studentleave',
            index=models.Index(fields=['end_date'], name='app_student_end_dat_a6bc07_idx'),
        ),
        migrations.AddIndex(
            model_name='studentleave',
            index=models.Index(fields=['student', 'status'], name='app_student_student_3872d5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentleave',
            index=models.Index(fields=['start_date', 'end_date'], name='app_student_start_d_819658_idx'),
        ),
        migrations.AddIndex(
            model_name='studentleave',
            index=models.Index(fields=['status', 'start_date'], name='app_student_status_670f69_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['course'], name='app_subject_course__cc6d41_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['period_or_year'], name='app_subject_period__8a2d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='app_subject_name_2bb7a5_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['course', 'period_or_year'], name='app_subject_course__db0db8_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name', 'course'], name='app_subject_name_1a4605_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'course', 'period_or_year')},
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['course'], name='app_routine_course__eb7541_idx'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['subject'], name='app_routine_subject_1d5d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['teacher'], name='app_routine_teacher_366026_idx'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['is_active'], name='app_routine_is_acti_e85aed_idx'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['period_or_year'], name='app_routine_period__ccc241_idx'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['course', 'period_or_year'], name='app_routine_course__20823d_idx'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['teacher', 'is_active'], name='app_routine_teacher_ca31c8_idx'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['subject', 'is_active'], name='app_routine_subject_dc7980_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routine',
            unique_together={('course', 'subject', 'teacher', 'start_time', 'end_time', 'period_or_year')},
        ),
        migrations.AddIndex(
            model_name='subjectprogress',
            index=models.Index(fields=['student'], name='app_subject_student_ebcf12_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectprogress',
            index=models.Index(fields=['subject'], name='app_subject_subject_0ab9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectprogress',
            index=models.Index(fields=['status'], name='app_subject_status_e0d5c5_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectprogress',
            index=models.Index(fields=['student', 'subject'], name='app_subject_student_85a2ec_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectprogress',
            index=models.Index(fields=['student', 'status'], name='app_subject_student_77f5d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectprogress',
            unique_together={('student', 'subject')},
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['phone'], name='app_staff_phone_048ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['designation'], name='app_staff_designa_a218a9_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_active'], name='app_staff_is_acti_e84a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['course'], name='app_staff_course__9328d1_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['designation', 'is_active'], name='app_staff_designa_9cf9ba_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['course', 'is_active'], name='app_staff_course__700e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['phone', 'is_active'], name='app_staff_phone_934f3a_idx'),
        ),
    ]
